name: Fork Sync

# Runs at 13:00 UTC every day
on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.2.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: 'specklesystems'
          head: 'main'
          base: 'main'